spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        show_sql: true
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_inserts: true
        order_updates: true

  datasource:
    password: password
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:

  liquibase:
    change-log: changelog/changelog-master.yml

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: Trace
