name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: app.jar
        path: target/jpa-workshop-0.0.1-SNAPSHOT.jar

  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: target/jpa-workshop-0.0.1-SNAPSHOT.jar
      - name: See jar file
        run: ls -la target
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest
    needs: [build]

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build-push]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Authenticate and deploy to Kubernetes
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
          KUBE_NAMESPACE: sindenis
        run: |
          echo "$KUBECONFIG_FILE" > kubeconfig.yaml
          kubectl config use-context cloud_okteto_com-context --kubeconfig=kubeconfig.yaml
          kubectl apply --kubeconfig=kubeconfig.yaml --namespace=$KUBE_NAMESPACE -f k8s
